api_platform:
    show_webby: true
    title: 'AMS Projet'
    description: 'Rest version of AMS Project.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/json']
    swagger:
        versions: [3]
